language: go

go:
  - master

script: go test -v ./test

before_deploy:
  - GOOS=linux GOARCH=amd64 go build -o ./bin/docker-machine-driver-proxmoxve.$GOOS.$GOARCH ./cmd/docker-machine-driver-proxmoxve
  - GOOS=linux GOARCH=arm64 go build -o ./bin/docker-machine-driver-proxmoxve.$GOOS.$GOARCH ./cmd/docker-machine-driver-proxmoxve
  - GOOS=linux GOARCH=arm go build -o bin/docker-machine-driver-proxmoxve.$GOOS.$GOARCH ./cmd/docker-machine-driver-proxmoxve
  - GOOS=darwin GOARCH=amd64 go build -o bin/docker-machine-driver-proxmoxve.$GOOS.$GOARCH ./cmd/docker-machine-driver-proxmoxve
  - GOOS=windows GOARCH=amd64 go build -o bin/docker-machine-driver-proxmoxve.$GOOS.$GOARCH ./cmd/docker-machine-driver-proxmoxve

deploy:
  provider: releases
  api_key: $release_token
  file: bin/*
  on:
    tags: true
