version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: make test
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: make build-all
      - persist_to_workspace:
          root: ./bin
          paths:
            - "*"

  deploy-to-github-release:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: ./bin
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./bin/
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy-to-github-release:
          requires:
            - build
          context: Github
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/